CREATE TABLE UNIDADE(
	COD_UNIDADE INT IDENTITY,
	NOME_UNIDADE VARCHAR(50) NOT NULL,


	CONSTRAINT PK_UNIDADE PRIMARY KEY (COD_UNIDADE),
);
INSERT INTO UNIDADE
	(NOME_UNIDADE)
	VALUES
	('PEÇAS'),
	('METRO'),
	('QUILOGRAMAS'),
	('DÚZIAS'),
	('PACOTE'),
	('CAIXA');
